ExternalProject_Add(libsoxr
    DEPENDS gcc
    URL "https://download.sourceforge.net/soxr/soxr-0.1.3-Source.tar.xz"
    URL_HASH SHA256=b111c15fdc8c029989330ff559184198c161100a59312f5dc19ddeb9b5a15889
    CMAKE_ARGS -DCMAKE_INSTALL_PREFIX=${MINGW_INSTALL_PREFIX} -DCMAKE_TOOLCHAIN_FILE=${TOOLCHAIN_FILE} -DBUILD_SHARED_LIBS=OFF -DBUILD_TESTS=OFF -DHAVE_WORDS_BIGENDIAN_EXITCODE=1 -DCMAKE_BUILD_TYPE=RelWithDebInfo
    BUILD_COMMAND ${CMAKE_MAKE_PROGRAM}
    INSTALL_COMMAND ${CMAKE_MAKE_PROGRAM} install
    LOG_DOWNLOAD 1 LOG_UPDATE 1 LOG_CONFIGURE 1 LOG_BUILD 1 LOG_INSTALL 1
)
